apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-debug
spec:
  selector:
    matchLabels:
      app: net-debug 
  replicas: 1 
  template:
    metadata:
      labels:
        app: net-debug
    spec:
      containers:
      - name: net-debug
        image: retvari/net-debug
        command: ["iperf"]
        args: ["-s","-u","-e"]
        securityContext:
          capabilities:
            add:
            - NET_RAW
        ports:
        - containerPort: 5001
          protocol: UDP
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: net-debug-lb-u
spec:
  type: LoadBalancer
  selector:
    app: net-debug
  ports:
    - protocol: UDP
      port: 5001
      targetPort: 5001
