FROM alpine


RUN apk add \
    ca-certificates cmake git make gcc pkgconfig openssl-dev alpine-sdk
    # pkg-config build-essential libssl-dev

RUN git clone https://github.com/quicr/quicrq/

WORKDIR /quicrq

RUN cmake .
RUN make

EXPOSE 4436/udp
CMD ["/quicrq/quicrq_app","-p","4436","client","127.0.0.1","s","30900","get:videotest1:/quicrq/test1.bin"]


