FROM alpine


RUN apk add \
    ca-certificates cmake git make gcc pkgconfig openssl-dev alpine-sdk
    # pkg-config build-essential libssl-dev

RUN git clone https://github.com/quicr/quicrq/

WORKDIR /quicrq

RUN cmake .
RUN make

EXPOSE 4433
CMD ["/quicrq_app","-c certs/cert.pem -k certs/key.pem -p 4433 server"]


