FROM alpine


RUN apk add \
    ca-certificates cmake git make gcc pkgconfig openssl-dev alpine-sdk
    # pkg-config build-essential libssl-dev

RUN git clone -b tinkering https://github.com/1majom/quicrq_tinkering

WORKDIR /quicrq_tinkering 

RUN cmake .
RUN make

EXPOSE 4437/udp
CMD ["sleep","3600000000"]


