apiVersion: v1
kind: Service
metadata:
  name: quicrq-server-headless
  labels:
    app: quicrq-server
spec:
  ports:
  - port: 4433
    protocol: UDP
  clusterIP: None
  selector:
    app: quicrq-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quicrq-server
spec:
  selector:
    matchLabels:
      app: quicrq-server
  serviceName: "quicrq-server"
  replicas: 1
  template:
    metadata:
      labels:
        app: quicrq-server
    spec:
      containers:
      - name: quicrq-server
        image: 1majom/quicrq:server
        securityContext:
          capabilities:
            add:
            - NET_RAW
        ports:
        - containerPort: 4433
          protocol: UDP
        imagePullPolicy: Always