apiVersion: apps/v1
kind: Deployment
metadata:
  name: quicrq-relay-between
  labels:
    app: quicrq-relay-between
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quicrq-relay-between
  template:
    metadata:
      labels:
        app: quicrq-relay-between
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "for i in {1..100}; do sleep 5; if nslookup quicrq-server-headless; then exit 0; fi; done;"]
      containers:
      - name: quicrq-relay
        image: 1majom/quicrq:relay-kube
        securityContext:
          capabilities:
            add:
            - NET_RAW
        ports:
        - containerPort: 30900
          protocol: UDP
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: quicrq-relay-headless
  labels:
    app: quicrq-relay-between
spec:
  ports:
  - port: 30900
    protocol: UDP
  clusterIP: None
  selector:
    app: quicrq-relay-between
