apiVersion: apps/v1
kind: Deployment
metadata:
  name: quicrq-server-2
spec:
  selector:
    matchLabels:
      app: quicrq-server 
  replicas: 1 
  template:
    metadata:
      labels:
        app: quicrq-server 
    spec:
      containers:
      - name: quicrq-server
        image: 1majom/quicrq:server
        securityContext:
          capabilities:
            add:
            - NET_RAW
        ports:
        - containerPort: 4433
          protocol: UDP
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: quicrq-server-lb-2
spec:
  type: LoadBalancer
  loadBalancerIP: 34.116.161.51
  selector:
    app: quicrq-server-2
  ports:
    - protocol: UDP
      port: 4433
      targetPort: 4433
---
apiVersion: v1
kind: Service
metadata:
  name: quicrq-server-headless
  labels:
    app: quicrq-server
spec:
  ports:
  - port: 4433
    protocol: UDP
  selector:
    app: quicrq-server