apiVersion: v1
kind: Service
metadata:
  name: quicrq-server-headless
  labels:
    app: quicrq-server
spec:
  ports:
  - port: 4433
    protocol: UDP
  clusterIP: None
  selector:
    app: quicrq-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quicrq-server
spec:
  selector:
    matchLabels:
      app: quicrq-server # has to match .spec.template.metadata.labels
  serviceName: "quicrq-server"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: quicrq-server # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: quicrq-server
        image: 1majom/quicrq:server
        ports:
        - containerPort: 4433
          protocol: UDP
        imagePullPolicy: Always
#kubectl expose deployment quicrq-server --port=4433 --target-port=4433 --name=quicrq-server-lb --type=LoadBalancer