apiVersion: apps/v1
kind: Deployment
metadata:
  name: quicrq-server
spec:
  selector:
    matchLabels:
      app: quicrq-server # has to match .spec.template.metadata.labels
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: quicrq-server # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: quicrq-server
        image: 1majom/quicrq:server
        securityContext:
          capabilities:
            add:
            - NET_RAW
        ports:
        - containerPort: 4433
          protocol: UDP
        imagePullPolicy: Always
